import { Inter } from 'next/font/google'
import './globals.css'
import ShopSwitcher from '@/components/shop-switcher'
import MainNav from '@/components/main-nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="border-b">
          <div className="flex h-16 items-center px-4">
            <ShopSwitcher />
            <MainNav className="mx-6" />
            
          </div>
        </div>
        {children}
        
        </body>
    </html>
  )
}
